### ISSUE TITLE
peer review

### ISSUE THREAD

**Issue by bradgarropy** [bradgarropy/labman-cli#48]
Pinging @austintoddj to take a look!

Would love some feedback on the [`readme`][readme] and the actual `labman` tool!

[readme]: https://github.com/bradgarropy/labman-cli#readme

**Comment by austintoddj** [comment]
Taking a look!

**Comment by austintoddj** [comment]
The readme looks really clean. It's informative and comprehensive. One addition that I always find helpful is when developers have a .gif of the cli tool in action right at the top, gives a nice overview of what the thing looks like right out of the box.

The tool is pretty straightforward. One of the only things I thought of was to perhaps have a warning pop when you're about to perform a destructive action:

```
Warning: You're about to remove everything, are you sure?  (Y/N)
```

But I really like it, just like rsync for label management!

**Comment by bradgarropy** [comment]
Thanks for the feedback man!

Couple more questions for you:

- Currently `labman` only supports the `rsync` style operation. Should I expand it to support the standard CRUD operations from the CLI, or would that be overkill for the purpose of the tool?
Example: `labman new bradgarropy/repo-name "label name" "label description" #123456`
- Do you think the `personal access token` login system is good enough for `v1`, or should I implement `oauth` from the CLI (which I struggled with earlier).
- Love the `gif` idea! Is there a specific tool you use to create them?

**Comment by austintoddj** [comment]
For an MVP, I'd say the project only needs to support the Rsync style operations. V2 could branch out. I'd say the same for OAuth, I think using PAT's is sufficient to give people an easy in-road. 

For Gifs, check out [Kap](https://getkap.co/)!

**Comment by austintoddj** [comment]
@bradgarropy Since I remembered the old tool I used to use, I'll throw it here, since it's relevant to the conversation:

https://asciinema.org

Super slick and easy to use. Maybe it'll come in handy on a future project!
